### ISSUE TITLE
setup on rock 3a 

### ISSUE THREAD

**Issue by flaep** [radxa/pyRock#7]
running setup on a rock 3a gives following error

> /root/pyrock/pyRock/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
running install
running build
running build_py
running build_ext
No processor detected
Warning! Detected and target processor mismatch.
Do you want to continue [Y/n]? n
Abort.

Is this expected? Is there a working python gpio library for rock 3a

**Comment by flaep** [comment]
if continue the setup anyway the init fails

> import os
> import sys
> 
> if not os.getegid() == 0:
>     sys.exit('Script must be run as root')
> 
> from time import sleep
> from pyRock.gpio import gpio
> 
> gpio.init()

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 1] Operation not permitted

I run python as root

**Comment by jack-ma** [comment]
pyRock only supports the original Radxa Rock in 2013. For newer ROCK series such as ROCK 3, ROCK 4, ROCK 5, the suggested GPIO library is WringX. Python support can be found:


https://github.com/wiringX/wiringX/tree/master/python
